name: Go package

on:
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: make build

      - name: Test
        run: make tests

      - name: Code style check
        run: make code-check

      - name: Vulnerabilities
        run: make check-security